//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteFinanceiroConsole.FinanceiroService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrejuizoPorPeca", Namespace="http://schemas.datacontract.org/2004/07/FinanceiroServiceWCF")]
    [System.SerializableAttribute()]
    public partial class PrejuizoPorPeca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPecaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPrejuizoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPeca {
            get {
                return this.CodigoPecaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPecaField, value) != true)) {
                    this.CodigoPecaField = value;
                    this.RaisePropertyChanged("CodigoPeca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPrejuizo {
            get {
                return this.TotalPrejuizoField;
            }
            set {
                if ((this.TotalPrejuizoField.Equals(value) != true)) {
                    this.TotalPrejuizoField = value;
                    this.RaisePropertyChanged("TotalPrejuizo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosFinanceiros", Namespace="http://schemas.datacontract.org/2004/07/FinanceiroServiceWCF")]
    [System.SerializableAttribute()]
    public partial class DadosFinanceiros : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPecaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CustoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LucroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrejuizoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TempoProducaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPeca {
            get {
                return this.CodigoPecaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPecaField, value) != true)) {
                    this.CodigoPecaField = value;
                    this.RaisePropertyChanged("CodigoPeca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Custo {
            get {
                return this.CustoField;
            }
            set {
                if ((this.CustoField.Equals(value) != true)) {
                    this.CustoField = value;
                    this.RaisePropertyChanged("Custo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Lucro {
            get {
                return this.LucroField;
            }
            set {
                if ((this.LucroField.Equals(value) != true)) {
                    this.LucroField = value;
                    this.RaisePropertyChanged("Lucro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Prejuizo {
            get {
                return this.PrejuizoField;
            }
            set {
                if ((this.PrejuizoField.Equals(value) != true)) {
                    this.PrejuizoField = value;
                    this.RaisePropertyChanged("Prejuizo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TempoProducao {
            get {
                return this.TempoProducaoField;
            }
            set {
                if ((this.TempoProducaoField.Equals(value) != true)) {
                    this.TempoProducaoField = value;
                    this.RaisePropertyChanged("TempoProducao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinanceiroService.IFinanceiroService")]
    public interface IFinanceiroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiroService/GetPecaMaiorPrejuizo", ReplyAction="http://tempuri.org/IFinanceiroService/GetPecaMaiorPrejuizoResponse")]
        string GetPecaMaiorPrejuizo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiroService/GetPecaMaiorPrejuizo", ReplyAction="http://tempuri.org/IFinanceiroService/GetPecaMaiorPrejuizoResponse")]
        System.Threading.Tasks.Task<string> GetPecaMaiorPrejuizoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiroService/GetCustoTotalProducao", ReplyAction="http://tempuri.org/IFinanceiroService/GetCustoTotalProducaoResponse")]
        decimal GetCustoTotalProducao(System.DateTime dataInicio, System.DateTime dataFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiroService/GetCustoTotalProducao", ReplyAction="http://tempuri.org/IFinanceiroService/GetCustoTotalProducaoResponse")]
        System.Threading.Tasks.Task<decimal> GetCustoTotalProducaoAsync(System.DateTime dataInicio, System.DateTime dataFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiroService/GetLucroTotal", ReplyAction="http://tempuri.org/IFinanceiroService/GetLucroTotalResponse")]
        decimal GetLucroTotal(System.DateTime dataInicio, System.DateTime dataFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiroService/GetLucroTotal", ReplyAction="http://tempuri.org/IFinanceiroService/GetLucroTotalResponse")]
        System.Threading.Tasks.Task<decimal> GetLucroTotalAsync(System.DateTime dataInicio, System.DateTime dataFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiroService/GetPrejuizoTotalPorPeca", ReplyAction="http://tempuri.org/IFinanceiroService/GetPrejuizoTotalPorPecaResponse")]
        ClienteFinanceiroConsole.FinanceiroService.PrejuizoPorPeca[] GetPrejuizoTotalPorPeca(System.DateTime dataInicio, System.DateTime dataFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiroService/GetPrejuizoTotalPorPeca", ReplyAction="http://tempuri.org/IFinanceiroService/GetPrejuizoTotalPorPecaResponse")]
        System.Threading.Tasks.Task<ClienteFinanceiroConsole.FinanceiroService.PrejuizoPorPeca[]> GetPrejuizoTotalPorPecaAsync(System.DateTime dataInicio, System.DateTime dataFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiroService/GetDadosFinanceirosPorPeca", ReplyAction="http://tempuri.org/IFinanceiroService/GetDadosFinanceirosPorPecaResponse")]
        ClienteFinanceiroConsole.FinanceiroService.DadosFinanceiros GetDadosFinanceirosPorPeca(string codigoPeca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiroService/GetDadosFinanceirosPorPeca", ReplyAction="http://tempuri.org/IFinanceiroService/GetDadosFinanceirosPorPecaResponse")]
        System.Threading.Tasks.Task<ClienteFinanceiroConsole.FinanceiroService.DadosFinanceiros> GetDadosFinanceirosPorPecaAsync(string codigoPeca);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinanceiroServiceChannel : ClienteFinanceiroConsole.FinanceiroService.IFinanceiroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinanceiroServiceClient : System.ServiceModel.ClientBase<ClienteFinanceiroConsole.FinanceiroService.IFinanceiroService>, ClienteFinanceiroConsole.FinanceiroService.IFinanceiroService {
        
        public FinanceiroServiceClient() {
        }
        
        public FinanceiroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinanceiroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceiroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceiroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPecaMaiorPrejuizo() {
            return base.Channel.GetPecaMaiorPrejuizo();
        }
        
        public System.Threading.Tasks.Task<string> GetPecaMaiorPrejuizoAsync() {
            return base.Channel.GetPecaMaiorPrejuizoAsync();
        }
        
        public decimal GetCustoTotalProducao(System.DateTime dataInicio, System.DateTime dataFim) {
            return base.Channel.GetCustoTotalProducao(dataInicio, dataFim);
        }
        
        public System.Threading.Tasks.Task<decimal> GetCustoTotalProducaoAsync(System.DateTime dataInicio, System.DateTime dataFim) {
            return base.Channel.GetCustoTotalProducaoAsync(dataInicio, dataFim);
        }
        
        public decimal GetLucroTotal(System.DateTime dataInicio, System.DateTime dataFim) {
            return base.Channel.GetLucroTotal(dataInicio, dataFim);
        }
        
        public System.Threading.Tasks.Task<decimal> GetLucroTotalAsync(System.DateTime dataInicio, System.DateTime dataFim) {
            return base.Channel.GetLucroTotalAsync(dataInicio, dataFim);
        }
        
        public ClienteFinanceiroConsole.FinanceiroService.PrejuizoPorPeca[] GetPrejuizoTotalPorPeca(System.DateTime dataInicio, System.DateTime dataFim) {
            return base.Channel.GetPrejuizoTotalPorPeca(dataInicio, dataFim);
        }
        
        public System.Threading.Tasks.Task<ClienteFinanceiroConsole.FinanceiroService.PrejuizoPorPeca[]> GetPrejuizoTotalPorPecaAsync(System.DateTime dataInicio, System.DateTime dataFim) {
            return base.Channel.GetPrejuizoTotalPorPecaAsync(dataInicio, dataFim);
        }
        
        public ClienteFinanceiroConsole.FinanceiroService.DadosFinanceiros GetDadosFinanceirosPorPeca(string codigoPeca) {
            return base.Channel.GetDadosFinanceirosPorPeca(codigoPeca);
        }
        
        public System.Threading.Tasks.Task<ClienteFinanceiroConsole.FinanceiroService.DadosFinanceiros> GetDadosFinanceirosPorPecaAsync(string codigoPeca) {
            return base.Channel.GetDadosFinanceirosPorPecaAsync(codigoPeca);
        }
    }
}
